### ISSUE TITLE
Unable to use the documented `import` from ESM

### ISSUE THREAD

**Issue by akauppi** [lukeed/totalist#4]
Importing `totals/sync` is not possible from an ES modules node project, in the documented way:

```
//import { totalist } from 'totalist/sync';     // "Directory import ... not supported"
import { totalist } from 'totalist/sync/index.mjs';
```

**Comment by lukeed** [comment]
Yup, this is planned as part of the next major. Adding `exports` is breaking, depending on the Node.js version. I was hoping to hold out until April so that I could do a sweep of new major versions across my packages.

**Comment by lukeed** [comment]
Closing for now, as native ESM is intentionally not in yet. Will be fixed in the future, as mentioned.

The documented usage works with any bundler/resolver since they don't share the same rules as Node's native ESM resolution. For now, in a native ESM environment, you must specify the full file path – as you've done.
